### ISSUE TITLE
This project can't work, because react-hot-loader config error

### ISSUE THREAD

**Issue by liangpure** [fdaciuk/workflow-reactjs#11]
Because  package.json dependency  "react-hot-loader": "next", react-hot-loader now in v4 beta, the current config can't work.
I try modify the config to fit react-hot-loader v4, but react-hot-loader still can't work.
Wish you fix it when you free. 
thank you for this library, I learn much from it.(￣▽￣)~

**Comment by matheusquintaes** [comment]
@liangpure try modify in package.json the dependency 'react-hot-loader' for version:
"react-hot-loader": "^3.0.0-beta.2",".

it worked here

**Comment by liangpure** [comment]
@matheusquintaes thanks.
Actually, make sure react-hot-loader is version 3,it will work.
I has created a pull request for change the dependency of react-hot-loader  to v4
[fix react-hot-loader v4 config error](https://github.com/fdaciuk/workflow-reactjs/pull/12)

**Comment by fdaciuk** [comment]
Hi @liangpure! Thanks for contribution! It's not time to update it yet, but I'll update the `package.json` with @matheusquintaes's suggestion =)

Thank you all =)

**Comment by fdaciuk** [comment]
Done! Version `3.0.0` is working fine for now =)
