### ISSUE TITLE
Error regarding Node version

### ISSUE THREAD

**Issue by fernandofragoso** [fdaciuk/workflow-reactjs#13]
I tried to 'yarn' the package but got the following error:

error upath@1.0.4: The engine "node" is incompatible with this module. Expected version ">=4 <=9".

I'm using Node 10.4. Would it be a nice PR if I try to get the things working in Node newer versions?
Or you already have a solution for this issue?

**Comment by fdaciuk** [comment]
Hi @fernandofragoso! It is an issue with some dependency, but you can just ignore engines using the following command:

```
yarn install --ignore-engines
```

Sorry for delay =)
