### ISSUE TITLE
React hot loader isn't working properly

### ISSUE THREAD

**Issue by victormiguez** [fdaciuk/workflow-reactjs#5]
Hey @fdaciuk!

It looks like after the dependencies update the hot loader stopped working, did you noticed this?
Probably it's a dependency version problem, but not sure yet.
I'm trying to figure it out.

**Comment by fdaciuk** [comment]
Hey @victormiguez! Try to delete `node_modules` and install all dependencies again, or just run `yarn update-packages` =)

**Comment by fdaciuk** [comment]
Let me know if it worked for you.

**Comment by victormiguez** [comment]
Thanks for the fast reply! :)

I did this, but still the same behavior. Here is my console output:

<img width="963" alt="captura de tela 2017-02-14 as 10 30 26" src="https://cloud.githubusercontent.com/assets/4250355/22929071/e9c32cf0-f2a0-11e6-9f92-f7d9779870c4.png">

Although it say that is updating, nothing happens.
This warning is new, it wasn't happening before, probably something related with the `async`.

Steps that I'm doing: 
- clone repo;
- `yarn update-packages`;
- `yarn start`

node version: `7.5.0`
yarn version: `0.19.1`

**Comment by fdaciuk** [comment]
Please, try:

- fork;
- run `yarn`;
- run `yarn start`.

This should works xD

**Comment by fdaciuk** [comment]
@victormiguez it worked?

**Comment by fdaciuk** [comment]
@victormiguez I'll close this issue, but if the solution doesn't work for you, we open it again, ok?

**Comment by victormiguez** [comment]
@fdaciuk still the same :/ But it's not a bug in your project, make sense to keep it closed.
I'm passing trough the same problem in other environments, looks like something is wrong with the last version of hot reloader.
If I find a solution I update here.
Thanks for the support! 👊

**Comment by fdaciuk** [comment]
Hey, let's fix it together! =)
Which node.js version are you using?
