### ISSUE TITLE
Sugestão - gerador de arquivos

### ISSUE THREAD

**Issue by devigor** [fdaciuk/workflow-reactjs#6]
Sugestão: usar o Slush para gerar os arquivos

**Comment by fdaciuk** [comment]
Opa @devigor! 
Vamos criar alguns geradores em breve, pois esse workflow tende a ficar maior.. para que não precise adicionar coisas ao seu projeto sem necessidade, vamos criar alguns scripts que automatizem o processo e instalem somente o que realmente for necessário =)

Provavelmente vamos criar scripts próprios ao invés de utilizar o slush, para não precisar de uma dependência a mais, mas a ideia é ótima!

Muito obrigado pela sugestão =) :dancer: :dancer: :sparkles:

**Comment by fdaciuk** [comment]
Bom, eu vou fechar a issue porque essa feature vai entrar de qualquer forma, mas ela será incluída conforme o andamento do curso =)
