### ISSUE TITLE
Observação

### ISSUE THREAD

**Issue by allergictoeng** [fdaciuk/workflow-reactjs#7]
Olá Fernando.
Estou fazendo a aula "React + Webpack #06", e dentro do webpack.config.js:
No vídeo está: 
# loader: 'babel'
Entretanto para mim funcionou:
# loader: 'babel-loader'
Não sei se mais tarde no curso há alguma explicação para isto, entretanto acredito que alguém pode ter o mesmo problema que o meu, peço desculpas se eu abri a Issue no repositório errado =)
Boa semana.

**Comment by fdaciuk** [comment]
Olá @allergictoeng! É que recentemente o `webpack` atualizou sua última versão para a `v2`, e isso trouxe algumas mudanças, como no caso do loader, que não é mais implícito o `-loader`, você precisa adicionar manualmente xD

Fique de olho nas versões dos módulos que dá pra seguir tranquilo =)

Qualquer dúvida só avisar! =)
