### ISSUE TITLE
help com o webpack-dev-server!

### ISSUE THREAD

**Issue by allergictoeng** [fdaciuk/workflow-reactjs#8]
Olá Fernando,
Estou tendo um probleminha com o hot loader, recebo a mensagem "Error: Cannot find module 'webpack-dev-server'"
- já tenho o webpack-dev-server instalado com a diretiva -g 

Abaixo uma imagem do erro e o repositório que criei para estudar (https://github.com/allergictoeng/react-webpack), obrigado desde já e boa semana.
  
![image](https://cloud.githubusercontent.com/assets/7969306/23288080/0c2e1e9a-fa20-11e6-96d9-8103e7421ab7.png)

**Comment by fdaciuk** [comment]
Fala @allergictoeng! O webpack lançou uma nova versão recentemente, com _breaking changes_. O que estamos vendo no curso para montar esse workflow é a v1, então você só precisa fazer o seguinte:

- Desinstale o `webpack` e o `webpack-dev-server` do seu projeto (que estão na v2);
- Instale a v1 deles: `npm install --save-dev webpack@1 webpack-dev-server@1`

Isso deve funcionar. Qualquer coisa me avise!
