### ISSUE TITLE
Module build failed when starting (SyntaxError on index.js)

### ISSUE THREAD

**Issue by willianribeiro** [fdaciuk/workflow-reactjs#9]
Hi! (-;
I'm having issues to start application.

I followed this steps:

- Download repository (zip file)
- Install dependencies: `yarn`
- Run `yarn start`

But when I run `yarn start` I get this error:

![image](https://cloud.githubusercontent.com/assets/3102551/24430588/a2cff9b8-13ed-11e7-9634-da35782c1005.png)

I don't change anything. am I missing something?

Thank You!

**Comment by willianribeiro** [comment]
The code that are triggering error is:

![image](https://cloud.githubusercontent.com/assets/3102551/24430688/42a20738-13ee-11e7-9a5c-994eb0d5779d.png)

**Comment by fdaciuk** [comment]
Hi @willianribeiro! Can you check if you have a `.babelrc` file on root of your project?

**Comment by willianribeiro** [comment]
The problem was exactly what you guessed!

I don't know why, but my project was without all the files who starts with _"."_ . Maybe I have copied and pasted by graphical interface and this files were hidden.

Thanks a lot!

**Comment by fdaciuk** [comment]
I'm glad you did it! As soon as possible, I'm going to automate this workflow to start a new project using a CLI tool =)
For now, try to clone it instead download a zip file, and everything will works like a charm :D

**Comment by willianribeiro** [comment]
Nice! A CLI tool is a great idea (-;
